CREATE TABLE PROJETOS
(
    PRO_NUMERO BIGSERIAL    NOT NULL,
    PRO_NOME   VARCHAR(255) NOT NULL UNIQUE,
    DEP_NUMERO BIGINT,
    CONSTRAINT PRO_PKEY PRIMARY KEY (PRO_NUMERO),
    CONSTRAINT PRO_FKEY FOREIGN KEY (DEP_NUMERO) REFERENCES DEPARTAMENTOS (DEP_NUMERO)
);