CREATE TABLE EMPREGADO_PROJETO
(
    EMPRO_ID      BIGSERIAL NOT NULL,
    EMP_NUMERO    BIGINT    NOT NULL,
    PRO_NUMERO    BIGINT    NOT NULL,
    EMPRO_INICIO  TIMESTAMP NOT NULL,
    EMPRO_TERMINO TIMESTAMP NOT NULL,
    CONSTRAINT EMPRO_PKEY PRIMARY KEY (EMPRO_ID),
    CONSTRAINT EMPRO_FKEY1 FOREIGN KEY (PRO_NUMERO) REFERENCES PROJETOS (PRO_NUMERO),
    CONSTRAINT EMPRO_FKEY2 FOREIGN KEY (EMP_NUMERO) REFERENCES EMPREGADOS (EMP_NUMERO)
);